version: 2

jobs:
  build:
    docker:
        - image: novopl/circleci:python
    steps:
      - checkout
      - restore_cache:
          key: deps-rev3-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: tox-rev1-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
      - run: python setup.py develop
      - run: tox
      - save_cache:
          key: deps-rev3-{{ checksum "requirements.txt" }}
          paths:
          - /usr/local/bin
          - /usr/local/lib/python3.6/site-packages
      - save_cache:
          key: tox-rev1-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
          paths:
          - .tox
      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: docs/html
          destination: docs

  release:
    docker:
      - image: novopl/circleci:python
    steps:
      - checkout
      - restore_cache:
          key: deps-rev3-{{ checksum "requirements.txt" }}
      - run: python setup.py develop
      - run: peltak release gen-pypirc
      - run: peltak release upload pypi
      - run: rm ~/.pypirc
      - run: peltak release tag
      - run: "git push origin v$(peltak version show --porcelain)"


workflows:
  version: 2
  full_pipe:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
