version: 2

jobs:
  build:
    docker:
      - image: novopl/python36:circleci
    steps:
      - checkout
      - restore_cache:
          key: deps-rev3-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: tox-rev1-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}

      - run:
          name: Setup peltak
          command: |
            pip uninstall peltak -y
            python setup.py develop

      - run: peltak lint
      - run: tox

      - save_cache:
          key: deps-rev3-{{ checksum "requirements.txt" }}
          paths:
          - /usr/local/bin
          - /usr/local/lib/python3.6/site-packages
      - save_cache:
          key: tox-rev1-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
          paths:
          - .tox

      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: docs/html
          destination: docs

      - run:
          name: Upload to pypi
          command: |
            peltak release gen-pypirc
            peltak release upload pypi
            rm ~/.pypirc
          filters:
            branches:
              only: master
      - run:
          name: Create release tag
          command: |
            peltak release tag
            git push origin v$(peltak version show --porcelain)
          filters:
            branches:
              only: master

workflows:
  version: 2
  full_pipe:
    jobs:
      - build
