version: 2

jobs:
  build:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "Pipfile.lock" }}

      - run:
          name: Setup peltak
          command: |
            which pip
            echo '== which pip ============================================='
            which python
            echo '== which python =========================================='
            python --version
            echo '== python --version ======================================'
            whoami
            echo '== whoami ================================================'
            pipenv lock -d
            echo '== pipenv lock -d ========================================'
            pipenv lock -d --requirements | tee requirements.txt
            echo '== pipenv lock -d --requirements ========================='
            pipenv install -d
            echo '== pipenv install -d ====================================='

      - save_cache:
          key: deps-rev1-{{ checksum "Pipfile.lock" }}
          paths:
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
            - .venv

      - run:
          name: Lint
          command: pipenv run peltak lint
      - restore_cache:
          name: Restore tox cache
          key: tox-rev1-{{ checksum "Pipfile.lock" }}
      - run:
          name: Test
          command: pipenv run tox
      - save_cache:
          name: Save tox cache
          key: tox-rev1-{{ checksum "Pipfile.lock" }}
          paths:
            - .tox

      - run:
          name: Build Documentation
          command: |
            pipenv run peltak docs --recreate --run-doctests
            mv docs/html docs/peltak-docs
            cd docs && zip -r ../.build/peltak-docs.zip peltak-docs

      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: .build/peltak-docs.zip


  release:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "Pipfile.lock" }}

      - run:
          name: Setup peltak
          command: |
            pipenv install -d
            echo '== pipenv install -d ====================================='

      - run:
          name: Upload to pypi
          command: |
            pipenv run peltak pypi configure
            pipenv run peltak pypi upload pypi
            rm ~/.pypirc

      - run:
          name: Create release tag
          command: |
            pipenv run peltak release tag -m "$(pipenv run peltak changelog)"
            git push origin v$(pipenv run peltak version --porcelain)

  docs:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "setup.py" }}

      - run:
          name: Setup
          command: |
            time pipenv run install -d
            echo '== peltak install -d ====================================='
            pipenv run peltak --help
            echo '== peltak --help ========================================='

      - run:
          name: Build docs
          command: pipenv run peltak docs

      - run:
          name: Deploy gh-pages
          command: |
            git checkout gh-pages
            cp -r docs/html/* ./
            git add .
            git config user.email ${GIT_EMAIL}
            git config user.name ${GIT_USER}
            git commit -nm "Docs build #${CIRCLECI_BUILD_NUM}"
            git push --no-verify origin gh-pages

workflows:
  version: 2
  main:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
      - docs:
          requires:
            - build
          filters:
            branches:
              only: master
