version: 2

jobs:
  build:
    docker:
        - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
      - run: pip install -r requirements.txt -r ops/devrequirements.txt
      - run: python setup.py develop
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
          paths:
          - /usr/local/bin
          - /usr/local/lib/python3.6/site-packages
      - run: peltak test
      - run: peltak docs
      # - run: peltak lint
      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: docs/html
          destination: docs

  release:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
      - run: pip install -r requirements.txt -r ops/devrequirements.txt
      - run: python setup.py develop
      - run: peltak release gen-pypirc
      - run: peltak release upload pypi
      - run: rm ~/.pypirc
      - run: peltak release tag
      - run: "git push origin v$(peltak version show --porcelain)"


workflows:
  version: 2
  full_pipe:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
