version: 2

jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
            - run: pip install -r requirements.txt -r ops/devrequirements.txt
            - run: python setup.py develop
            - save_cache:
                key: deps-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
                paths:
                - /usr/local/bin
                - /usr/local/lib/python3.6/site-packages
    test:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
            - run: python setup.py develop
            - run: peltak test
            - run: paltak docs
           #  - run: peltak lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
           - build
