version: 2

jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
            - run: sudo pip install -U pip setuptoools
            - restore_cache:
                key: deps-{{ checksum requirements.txt }}-{{ checksum ops/requirements.txt }}
            - run: sudo pip install -r requirements.txt -r ops/devrequirements.txt
            - save_cache:
                key: deps-{{ checksum requirements.txt }}-{{ checksum ops/requirements.txt }}
                paths:
                - /usr/local/bin
                - /usr/local/lib/python3.6/site-packages
            - run fab lint
            - run fab test
            - run fab docs
