version: 2

jobs:
  build:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev4-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: tox-rev2-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}

      - run:
          name: Setup peltak
          command: |
            which pip
            which python
            python --version
            whoami
            pip freeze
            pip install -r ops/devrequirements.txt
            pip uninstall peltak -y || true
            python setup.py develop

      - run:
          name: Lint
          command: peltak lint
      - run:
          name: Test
          command: tox
      - run:
          name: Build Documentation
          command: |
            peltak docs --recreate --run-doctests
            mv docs/html docs/peltak-docs
            cd docs && zip -r ../.build/peltak-docs.zip peltak-docs

      - save_cache:
          key: deps-rev4-{{ checksum "requirements.txt" }}
          paths:
          - /usr/local/bin
          - /usr/local/lib/python3.6/site-packages
      - save_cache:
          key: tox-rev2-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
          paths:
          - .tox

      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: .build/peltak-docs.zip


  release:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev3-{{ checksum "requirements.txt" }}
      - run:
          name: Setup peltak
          command: |
            pip uninstall peltak -y
            python setup.py develop
      - run:
          name: Upload to pypi
          command: |
            peltak pypi configure
            peltak pypi upload pypi
            rm ~/.pypirc
      - run:
          name: Create release tag
          command: |
            peltak release tag
            git push origin v$(peltak version --porcelain)


workflows:
  version: 2
  main:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
